version: "3.9"
services:
  discovery:
    build:  ../DiscoveryServer
    ports:
      - "8761:8761"
    image: "discovery-server"
  hotel_A:
    build:  ../Hotel
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8080:8080"
    image: "hotel-service"
  hotel_B:
    build:  ../Hotel
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8081:8080"
    image: "hotel-service"
  flight_A:
    build:  ../Flight
    command: --spring.datasource.url=jdbc:h2:file:./Database/Data/Flights;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    volumes:
      - type: bind
        source: ./src/Database
        target: /flight_A
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8085:8085"
    image: "flight-service"
  excursion_A:
    build:  ../Excursion
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8087:8087"
    image: "excursion-service"
  gateway:
    build: ../gateway-server
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8762:8762"
    image: "gateway-server"